# Generated by Django 5.1.1 on 2024-10-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_examroom_unique_code_alter_examroom_google_form_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examroom',
            name='unique_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
