# Generated by Django 5.1.1 on 2024-10-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_student_end_time_alter_student_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
