# Generated by Django 5.1.1 on 2024-10-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_student_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
