# Generated by Django 5.1.1 on 2024-10-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_student_end_time_alter_student_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='log',
            field=models.TextField(default=''),
        ),
    ]
