# Generated by Django 5.1.1 on 2024-10-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_student_log_student_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
